### ISSUE TITLE
Disable compression if Kafka is configured to compress log segments

### ISSUE THREAD

**Issue by mdedetrich** [aiven/tiered-storage-for-apache-kafka#129]
# What is currently missing?

Currently with this plugin, compression is forcefully enabled even if it doesn't make sense in certain cases

# How could this be improved?

The plugin should detect if Kafka has compression enabled for a specific topic and if so not to compress within the plugin. This can also help deal with the current ongoing issue in fetching specific byte ranges (see https://github.com/aiven/tiered-storage-for-apache-kafka/issues/127)

# Is this a feature you would work on yourself?

* [ ] I plan to open a pull request for this feature

**Comment by jeqo** [comment]
Implemented by #230
