### ISSUE TITLE
[New implementation] Unify terms "encryption key" and "secret key"

### ISSUE THREAD

**Issue by ivanyu** [aiven/tiered-storage-for-apache-kafka#166]
AES keys should be named consistently.

**Comment by ivanyu** [comment]
@jeqo after browsing the internet, it seems the most correct name should be "data encryption key" or just "data key" for shortness. We can also use just `key` in the manifest JSON (there it's clear from the context).

**Comment by jeqo** [comment]
Thanks! Let's stick to dataKey whenever possible then, as we are using the term key for Object Keys already.
