### ISSUE TITLE
[New implementation] Consider renaming object.storage.factory setting to something better

### ISSUE THREAD

**Issue by ivanyu** [aiven/tiered-storage-for-apache-kafka#177]

**Comment by ivanyu** [comment]
Yes, this is pretty good. Let's do a rename once we've done with the flow of PRs

**Comment by jeqo** [comment]
Related discussion: https://github.com/aiven/tiered-storage-for-apache-kafka/pull/227

**Comment by jeqo** [comment]
Following up the discussion on #227, I would like to propose:

- Rename `ObjectStorageFactory` to `StorageBackEnd`
- Move `FileFetcher`, `FileUploader`, `FileDeleter` methods to `StorageBackEnd`
- Make `FileSystemStorage` and `S3Storage` to implement `StorageBackEnd` interface
- Move `configure` from `*StorageFactory` to `*Storage`
- Remove `*StorageFactory`
- Remove `File*`
- Rename configuration `object.storage.factory` to `storage.backend.class.name` (following other similar configs in Kafka)
- Rename configuration `storage.*` for Storage configs

cc @AnatolyPopov @ivanyu

**Comment by ivanyu** [comment]
So, effectively the `UniversalRemoteStorageManagerConfig` becomes the factory for storages, if I understand the idea. Sounds good.

I propose to `BackEnd` -> `Backend` as it's more widely used in the industry.

I also propose to have a different instances of the storage for uploading and downloading even after refactoring, so they don't have implicit contention on anything in their completely different use cases.

**Comment by jeqo** [comment]
Sure, I have updated the proposal.

If we want to keep to instances, it would be better to keep two different interfaces. I have reflected that on the proposal as well.

**Comment by jeqo** [comment]
Sure. I'd lean for not group them to have a instance per operation type.

I'm still hesitant if the implicit contention mentioned before needs to be solved at this level, or if already solved by the back-end client. But we can check later if needed when more back-ends are adopted.

See #234
