### ISSUE TITLE
[New implementation] Review project structure

### ISSUE THREAD

**Issue by ivanyu** [aiven/tiered-storage-for-apache-kafka#201]
Proposal:
1. Rename project `commons` -> `core`.
2. Don't have `commons` or `core` in the package name, so the RSM FQN is `io.aiven.kafka.tieredstorage.RemoteStorageManager`.
3. ~[Done in #236] Delete (the old) `s3`.~
4. Create the `storage` project.
5. Extract the current S3 implementation to `storage.s3` subproject.
6. Consider doing the same with the FS implementation. However, this may be problematic as `core` depends on the file system implementation (for tests). Maybe we should keep it in `core` after all, it's supposed to be a test backend anyway.
7. Tidy the Gradle dependency lists.

**Comment by jeqo** [comment]
Should we include `...tieredstorage.rlsm...` for Remote Log Storage Manager to the namespace? Considering Metadata Manager could also be implemented as part of this project. wdyt?

**Comment by ivanyu** [comment]
I'm not sure, sounds a bit overhead: the class name would be a good differentiation by itself. In the Kafka code, they have `RemoteLogMetadataManager` and `RemoteStorageManager` interfaces in the same package.

**Comment by jeqo** [comment]
Ob, haven't think about that. Thanks! 
The proposal looks sound to me then.
