### ISSUE TITLE
[New implementation] Decide on the RSM class name

### ISSUE THREAD

**Issue by ivanyu** [aiven/tiered-storage-for-apache-kafka#212]
Some ideas:
1. Keep the current `UniversalRemoteStorageManager`.
2. Rename it to just `RemoteStorageManager`. I don't see a problem that it's the same name as the interface, the FQN resolves the ambiguity.
3. Another name?

**Comment by jeqo** [comment]
What about `CommonRemoteStorageManager` not that different from URSM, but represents a bit more concretely what the class does.
Also, option 2 seems appealing.

**Comment by ivanyu** [comment]
I like option 2 as well

**Comment by AnatolyPopov** [comment]
Option 2 sounds good to me.

**Comment by ivanyu** [comment]
Ok, let's go for 2 now. Before we do the first release(s), we can always re-evaluate.
