### ISSUE TITLE
Is branch 3.3-2022-10-06-tiered-storage ready to be used?

### ISSUE THREAD

**Issue by HenryCaiHaiying** [aiven/tiered-storage-for-apache-kafka#224]
# What can we help you with?

# Where would you expect to find this information?

**Comment by HenryCaiHaiying** [comment]
Hi, I saw this PR https://github.com/aiven/tiered-storage-for-apache-kafka/commit/fd19a107a485e212d097c1771429c64f43f240cb reverts the kafka branch from 3.3 back to 3.0, is branch 3.3-2022-10-06-tiered storage ready to use?  @jeqo @mdedetrich

**Comment by ivanyu** [comment]
Hi @HenryCaiHaiying 
Not yet, there is a couple of bugs to fix in 3.3

**Comment by jeqo** [comment]
I would say it's ready now. 3.3 is used here: https://github.com/aiven/tiered-storage-for-apache-kafka/pull/262

Will close this one once #262 is merged.
